/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar;

import org.eclipse.emf.ecore.EStructuralFeature;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class RezeptFollowSetProvider {
	
	public static int terminalsIndex;
	public final static com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.IRezeptExpectedElement TERMINALS[] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.IRezeptExpectedElement[162];
	
	public static int featureIndex;
	public final static EStructuralFeature[] FEATURES = new EStructuralFeature[20];
	
	public static int linkIndex;
	public final static com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] LINKS = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[30];
	
	public final static com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] EMPTY_LINK_ARRAY = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[0];
	
	public static void initializeTerminals0() {
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_6_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_8_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_4);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_5);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_6);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_7);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_8);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_9);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_10);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_11);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_12);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_13);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_14);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_15);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_16);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_17_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_18);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_17_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_17_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_0_0_0_17_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_5_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_4);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_5);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_7_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_4_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_9_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_10);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_7_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_2_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_9_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_1_0_0_9_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_2_0_0_1_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_2_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_4);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_5);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_6_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_7);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_6_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_8);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_3_0_0_9);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_4_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_4_0_0_2_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_4_0_0_2_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_5_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_5_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_6_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_6_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_7_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_7_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_7_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_8_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_8_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_3_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_17_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_18_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_3_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_3_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_5_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_6_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_10_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_8_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_9_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_10);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_5_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_5_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_6_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_6_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_8_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_8_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_9_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_9_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_11);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_12);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_9_0_0_13);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_10_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_10_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_10_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_4);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_5);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_6_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_7);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_6_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_6_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_8);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_9);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_10_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_11_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_12);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_23_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_24_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_11_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_11_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_13);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_14);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_12_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_13_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_14_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_15_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_16_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_19_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_19);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_20_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_21_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_22_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_25_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_11_0_0_22);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_12_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_12_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_13_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_13_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_14_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_14_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_15_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_15_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_15_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_15_0_0_4);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_16_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_17_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_17_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_17_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_17_0_0_4);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_18_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_19_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_20_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_21_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_22_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_23_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_23_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_23_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_23_0_0_4);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_24_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_24_0_0_2);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_24_0_0_3);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_26_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_27_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_25_0_0_2_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_25_0_0_3_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_25_0_0_4_0_0_0);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedCsString(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_25_0_0_5);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_25_0_0_2_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_25_0_0_3_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_25_0_0_4_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_26_0_0_1);
		TERMINALS[terminalsIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptExpectedStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.grammar.RezeptGrammarInformationProvider.REZEPT_27_0_0_1);
	}
	
	public static void initializeTerminals() {
		initializeTerminals0();
	}
	
	public static void initializeFeatures0() {
		featureIndex = 0;
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProjektBeschreibung().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.PROJEKT_BESCHREIBUNG__BUCH);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBuchBeschreibung().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.BUCH_BESCHREIBUNG__IMPORTS);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBuchBeschreibung().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.BUCH_BESCHREIBUNG__AUTOREN);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBuchBeschreibung().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.BUCH_BESCHREIBUNG__ABSATZ);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBuchBeschreibung().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.BUCH_BESCHREIBUNG__LIZENZ);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezeptliste().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.REZEPTLISTE__IMPORTS);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezeptliste().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.REZEPTLISTE__REZEPTE);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProduktliste().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.PRODUKTLISTE__PRODUKTE);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProdukt().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.PRODUKT__MENGE);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProdukt().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.PRODUKT__PREIS);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.REZEPT__QUELLE);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.REZEPT__TAGS);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.REZEPT__NOTIZEN);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.REZEPT__BILDER);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.REZEPT__PRODUKTE);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.REZEPT__ZUTATEN);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getZutat().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.ZUTAT__MENGE);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.REZEPT__SCHRITTE);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getArbeitsschritt().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.ARBEITSSCHRITT__NOTIZ);
		FEATURES[featureIndex++] = com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBild().getEStructuralFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.BILD__ABLAGE_ORT);
	}
	
	public static void initializeFeatures() {
		initializeFeatures0();
	}
	
	public static void initializeLinks0() {
		linkIndex = 0;
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBuchBeschreibung(), FEATURES[0]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezeptImport(), FEATURES[1]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAutor(), FEATURES[2]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getLizenz(), FEATURES[4]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAbsatz(), FEATURES[3]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProduktImport(), FEATURES[5]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept(), FEATURES[6]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProdukt(), FEATURES[7]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBestimmteMenge(), FEATURES[8]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getUnbestimmteMenge(), FEATURES[8]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getPreis(), FEATURES[9]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getLiteraturquelle(), FEATURES[10]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getPersonenquelle(), FEATURES[10]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getStoffTag(), FEATURES[11]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBenutzerTag(), FEATURES[11]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getDiaetTag(), FEATURES[11]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProduktRef(), FEATURES[14]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getZutat(), FEATURES[15]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getArbeitsschritt(), FEATURES[17]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getTipp(), FEATURES[12]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getKommentar(), FEATURES[12]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAnmerkung(), FEATURES[12]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBild(), FEATURES[13]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBestimmteMenge(), FEATURES[16]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getUnbestimmteMenge(), FEATURES[16]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getTipp(), FEATURES[18]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getKommentar(), FEATURES[18]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAnmerkung(), FEATURES[18]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getInternetPfad(), FEATURES[19]);
		LINKS[linkIndex++] = new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getLokalerPfad(), FEATURES[19]);
	}
	
	public static void initializeLinks() {
		initializeLinks0();
	}
	
	public static void wire0() {
		TERMINALS[0].addFollower(TERMINALS[3], EMPTY_LINK_ARRAY);
		TERMINALS[3].addFollower(TERMINALS[4], EMPTY_LINK_ARRAY);
		TERMINALS[4].addFollower(TERMINALS[5], EMPTY_LINK_ARRAY);
		TERMINALS[5].addFollower(TERMINALS[6], EMPTY_LINK_ARRAY);
		TERMINALS[6].addFollower(TERMINALS[7], EMPTY_LINK_ARRAY);
		TERMINALS[7].addFollower(TERMINALS[8], EMPTY_LINK_ARRAY);
		TERMINALS[8].addFollower(TERMINALS[9], EMPTY_LINK_ARRAY);
		TERMINALS[9].addFollower(TERMINALS[10], EMPTY_LINK_ARRAY);
		TERMINALS[10].addFollower(TERMINALS[11], EMPTY_LINK_ARRAY);
		TERMINALS[11].addFollower(TERMINALS[12], EMPTY_LINK_ARRAY);
		TERMINALS[12].addFollower(TERMINALS[13], EMPTY_LINK_ARRAY);
		TERMINALS[13].addFollower(TERMINALS[14], EMPTY_LINK_ARRAY);
		TERMINALS[14].addFollower(TERMINALS[15], EMPTY_LINK_ARRAY);
		TERMINALS[15].addFollower(TERMINALS[16], EMPTY_LINK_ARRAY);
		TERMINALS[16].addFollower(TERMINALS[17], EMPTY_LINK_ARRAY);
		TERMINALS[17].addFollower(TERMINALS[18], EMPTY_LINK_ARRAY);
		TERMINALS[18].addFollower(TERMINALS[19], EMPTY_LINK_ARRAY);
		TERMINALS[18].addFollower(TERMINALS[20], EMPTY_LINK_ARRAY);
		TERMINALS[19].addFollower(TERMINALS[21], EMPTY_LINK_ARRAY);
		TERMINALS[21].addFollower(TERMINALS[22], EMPTY_LINK_ARRAY);
		TERMINALS[22].addFollower(TERMINALS[23], EMPTY_LINK_ARRAY);
		TERMINALS[23].addFollower(TERMINALS[20], EMPTY_LINK_ARRAY);
		TERMINALS[20].addFollower(TERMINALS[24], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBuchBeschreibung(), FEATURES[0]), });
		TERMINALS[24].addFollower(TERMINALS[25], EMPTY_LINK_ARRAY);
		TERMINALS[25].addFollower(TERMINALS[26], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezeptImport(), FEATURES[1]), });
		TERMINALS[25].addFollower(TERMINALS[27], EMPTY_LINK_ARRAY);
		TERMINALS[27].addFollower(TERMINALS[28], EMPTY_LINK_ARRAY);
		TERMINALS[28].addFollower(TERMINALS[29], EMPTY_LINK_ARRAY);
		TERMINALS[29].addFollower(TERMINALS[30], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAutor(), FEATURES[2]), });
		TERMINALS[31].addFollower(TERMINALS[35], EMPTY_LINK_ARRAY);
		TERMINALS[35].addFollower(TERMINALS[36], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAbsatz(), FEATURES[3]), });
		TERMINALS[35].addFollower(TERMINALS[32], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getLizenz(), FEATURES[4]), });
		TERMINALS[35].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[35].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[33].addFollower(TERMINALS[37], EMPTY_LINK_ARRAY);
		TERMINALS[37].addFollower(TERMINALS[38], EMPTY_LINK_ARRAY);
		TERMINALS[38].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[36].addFollower(TERMINALS[39], EMPTY_LINK_ARRAY);
		TERMINALS[36].addFollower(TERMINALS[40], EMPTY_LINK_ARRAY);
		TERMINALS[39].addFollower(TERMINALS[40], EMPTY_LINK_ARRAY);
		TERMINALS[40].addFollower(TERMINALS[36], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAbsatz(), FEATURES[3]), });
		TERMINALS[40].addFollower(TERMINALS[32], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getLizenz(), FEATURES[4]), });
		TERMINALS[40].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[40].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[30].addFollower(TERMINALS[41], EMPTY_LINK_ARRAY);
		TERMINALS[41].addFollower(TERMINALS[42], EMPTY_LINK_ARRAY);
		TERMINALS[42].addFollower(TERMINALS[43], EMPTY_LINK_ARRAY);
		TERMINALS[43].addFollower(TERMINALS[44], EMPTY_LINK_ARRAY);
		TERMINALS[44].addFollower(TERMINALS[45], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[46], EMPTY_LINK_ARRAY);
		TERMINALS[45].addFollower(TERMINALS[47], EMPTY_LINK_ARRAY);
		TERMINALS[46].addFollower(TERMINALS[48], EMPTY_LINK_ARRAY);
		TERMINALS[48].addFollower(TERMINALS[47], EMPTY_LINK_ARRAY);
		TERMINALS[47].addFollower(TERMINALS[49], EMPTY_LINK_ARRAY);
		TERMINALS[49].addFollower(TERMINALS[50], EMPTY_LINK_ARRAY);
		TERMINALS[50].addFollower(TERMINALS[30], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAutor(), FEATURES[2]), });
		TERMINALS[50].addFollower(TERMINALS[31], EMPTY_LINK_ARRAY);
		TERMINALS[50].addFollower(TERMINALS[32], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getLizenz(), FEATURES[4]), });
		TERMINALS[50].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[50].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[32].addFollower(TERMINALS[51], EMPTY_LINK_ARRAY);
		TERMINALS[51].addFollower(TERMINALS[52], EMPTY_LINK_ARRAY);
		TERMINALS[51].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[51].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[52].addFollower(TERMINALS[53], EMPTY_LINK_ARRAY);
		TERMINALS[53].addFollower(TERMINALS[33], EMPTY_LINK_ARRAY);
		TERMINALS[53].addFollower(TERMINALS[34], EMPTY_LINK_ARRAY);
		TERMINALS[26].addFollower(TERMINALS[54], EMPTY_LINK_ARRAY);
		TERMINALS[54].addFollower(TERMINALS[55], EMPTY_LINK_ARRAY);
		TERMINALS[55].addFollower(TERMINALS[26], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezeptImport(), FEATURES[1]), });
		TERMINALS[55].addFollower(TERMINALS[27], EMPTY_LINK_ARRAY);
		TERMINALS[1].addFollower(TERMINALS[56], EMPTY_LINK_ARRAY);
		TERMINALS[56].addFollower(TERMINALS[57], EMPTY_LINK_ARRAY);
		TERMINALS[57].addFollower(TERMINALS[58], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProduktImport(), FEATURES[5]), });
		TERMINALS[57].addFollower(TERMINALS[59], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept(), FEATURES[6]), });
		TERMINALS[58].addFollower(TERMINALS[60], EMPTY_LINK_ARRAY);
		TERMINALS[60].addFollower(TERMINALS[61], EMPTY_LINK_ARRAY);
		TERMINALS[61].addFollower(TERMINALS[58], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProduktImport(), FEATURES[5]), });
		TERMINALS[61].addFollower(TERMINALS[59], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept(), FEATURES[6]), });
		TERMINALS[2].addFollower(TERMINALS[62], EMPTY_LINK_ARRAY);
		TERMINALS[62].addFollower(TERMINALS[63], EMPTY_LINK_ARRAY);
		TERMINALS[63].addFollower(TERMINALS[64], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProdukt(), FEATURES[7]), });
		TERMINALS[64].addFollower(TERMINALS[65], EMPTY_LINK_ARRAY);
		TERMINALS[65].addFollower(TERMINALS[66], EMPTY_LINK_ARRAY);
		TERMINALS[66].addFollower(TERMINALS[67], EMPTY_LINK_ARRAY);
		TERMINALS[66].addFollower(TERMINALS[68], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBestimmteMenge(), FEATURES[8]), });
		TERMINALS[66].addFollower(TERMINALS[69], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getUnbestimmteMenge(), FEATURES[8]), });
		TERMINALS[67].addFollower(TERMINALS[70], EMPTY_LINK_ARRAY);
		TERMINALS[70].addFollower(TERMINALS[71], EMPTY_LINK_ARRAY);
		TERMINALS[71].addFollower(TERMINALS[68], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBestimmteMenge(), FEATURES[8]), });
		TERMINALS[71].addFollower(TERMINALS[69], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getUnbestimmteMenge(), FEATURES[8]), });
		TERMINALS[72].addFollower(TERMINALS[78], EMPTY_LINK_ARRAY);
		TERMINALS[78].addFollower(TERMINALS[79], EMPTY_LINK_ARRAY);
		TERMINALS[79].addFollower(TERMINALS[73], EMPTY_LINK_ARRAY);
		TERMINALS[79].addFollower(TERMINALS[74], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getPreis(), FEATURES[9]), });
		TERMINALS[79].addFollower(TERMINALS[75], EMPTY_LINK_ARRAY);
		TERMINALS[79].addFollower(TERMINALS[76], EMPTY_LINK_ARRAY);
		TERMINALS[79].addFollower(TERMINALS[77], EMPTY_LINK_ARRAY);
		TERMINALS[73].addFollower(TERMINALS[80], EMPTY_LINK_ARRAY);
		TERMINALS[80].addFollower(TERMINALS[81], EMPTY_LINK_ARRAY);
		TERMINALS[81].addFollower(TERMINALS[74], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getPreis(), FEATURES[9]), });
		TERMINALS[81].addFollower(TERMINALS[75], EMPTY_LINK_ARRAY);
		TERMINALS[81].addFollower(TERMINALS[76], EMPTY_LINK_ARRAY);
		TERMINALS[81].addFollower(TERMINALS[77], EMPTY_LINK_ARRAY);
		TERMINALS[75].addFollower(TERMINALS[82], EMPTY_LINK_ARRAY);
		TERMINALS[82].addFollower(TERMINALS[83], EMPTY_LINK_ARRAY);
		TERMINALS[83].addFollower(TERMINALS[76], EMPTY_LINK_ARRAY);
		TERMINALS[83].addFollower(TERMINALS[77], EMPTY_LINK_ARRAY);
		TERMINALS[76].addFollower(TERMINALS[84], EMPTY_LINK_ARRAY);
		TERMINALS[84].addFollower(TERMINALS[85], EMPTY_LINK_ARRAY);
		TERMINALS[85].addFollower(TERMINALS[77], EMPTY_LINK_ARRAY);
		TERMINALS[77].addFollower(TERMINALS[86], EMPTY_LINK_ARRAY);
		TERMINALS[86].addFollower(TERMINALS[87], EMPTY_LINK_ARRAY);
		TERMINALS[87].addFollower(TERMINALS[88], EMPTY_LINK_ARRAY);
		TERMINALS[88].addFollower(TERMINALS[64], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProdukt(), FEATURES[7]), });
		TERMINALS[74].addFollower(TERMINALS[89], EMPTY_LINK_ARRAY);
		TERMINALS[89].addFollower(TERMINALS[90], EMPTY_LINK_ARRAY);
		TERMINALS[90].addFollower(TERMINALS[91], EMPTY_LINK_ARRAY);
		TERMINALS[91].addFollower(TERMINALS[75], EMPTY_LINK_ARRAY);
		TERMINALS[91].addFollower(TERMINALS[76], EMPTY_LINK_ARRAY);
		TERMINALS[91].addFollower(TERMINALS[77], EMPTY_LINK_ARRAY);
		TERMINALS[59].addFollower(TERMINALS[92], EMPTY_LINK_ARRAY);
		TERMINALS[92].addFollower(TERMINALS[93], EMPTY_LINK_ARRAY);
		TERMINALS[93].addFollower(TERMINALS[94], EMPTY_LINK_ARRAY);
		TERMINALS[94].addFollower(TERMINALS[95], EMPTY_LINK_ARRAY);
		TERMINALS[95].addFollower(TERMINALS[96], EMPTY_LINK_ARRAY);
		TERMINALS[96].addFollower(TERMINALS[97], EMPTY_LINK_ARRAY);
		TERMINALS[96].addFollower(TERMINALS[98], EMPTY_LINK_ARRAY);
		TERMINALS[97].addFollower(TERMINALS[99], EMPTY_LINK_ARRAY);
		TERMINALS[99].addFollower(TERMINALS[100], EMPTY_LINK_ARRAY);
		TERMINALS[100].addFollower(TERMINALS[98], EMPTY_LINK_ARRAY);
		TERMINALS[98].addFollower(TERMINALS[101], EMPTY_LINK_ARRAY);
		TERMINALS[101].addFollower(TERMINALS[102], EMPTY_LINK_ARRAY);
		TERMINALS[102].addFollower(TERMINALS[103], EMPTY_LINK_ARRAY);
		TERMINALS[102].addFollower(TERMINALS[104], EMPTY_LINK_ARRAY);
		TERMINALS[102].addFollower(TERMINALS[105], EMPTY_LINK_ARRAY);
		TERMINALS[103].addFollower(TERMINALS[106], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getLiteraturquelle(), FEATURES[10]), });
		TERMINALS[103].addFollower(TERMINALS[107], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getPersonenquelle(), FEATURES[10]), });
		TERMINALS[104].addFollower(TERMINALS[108], EMPTY_LINK_ARRAY);
		TERMINALS[108].addFollower(TERMINALS[109], EMPTY_LINK_ARRAY);
		TERMINALS[109].addFollower(TERMINALS[105], EMPTY_LINK_ARRAY);
		TERMINALS[105].addFollower(TERMINALS[110], EMPTY_LINK_ARRAY);
		TERMINALS[110].addFollower(TERMINALS[111], EMPTY_LINK_ARRAY);
		TERMINALS[111].addFollower(TERMINALS[112], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getStoffTag(), FEATURES[11]), });
		TERMINALS[111].addFollower(TERMINALS[113], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBenutzerTag(), FEATURES[11]), });
		TERMINALS[111].addFollower(TERMINALS[114], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getDiaetTag(), FEATURES[11]), });
		TERMINALS[118].addFollower(TERMINALS[119], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getTipp(), FEATURES[12]), });
		TERMINALS[118].addFollower(TERMINALS[120], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getKommentar(), FEATURES[12]), });
		TERMINALS[118].addFollower(TERMINALS[121], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAnmerkung(), FEATURES[12]), });
		TERMINALS[118].addFollower(TERMINALS[122], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBild(), FEATURES[13]), });
		TERMINALS[118].addFollower(TERMINALS[123], EMPTY_LINK_ARRAY);
		TERMINALS[123].addFollower(TERMINALS[59], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getRezept(), FEATURES[6]), });
		TERMINALS[112].addFollower(TERMINALS[124], EMPTY_LINK_ARRAY);
		TERMINALS[124].addFollower(TERMINALS[125], EMPTY_LINK_ARRAY);
		TERMINALS[125].addFollower(TERMINALS[112], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getStoffTag(), FEATURES[11]), });
		TERMINALS[125].addFollower(TERMINALS[113], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBenutzerTag(), FEATURES[11]), });
		TERMINALS[125].addFollower(TERMINALS[114], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getDiaetTag(), FEATURES[11]), });
		TERMINALS[125].addFollower(TERMINALS[115], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProduktRef(), FEATURES[14]), });
		TERMINALS[125].addFollower(TERMINALS[116], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getZutat(), FEATURES[15]), });
		TERMINALS[113].addFollower(TERMINALS[126], EMPTY_LINK_ARRAY);
		TERMINALS[126].addFollower(TERMINALS[127], EMPTY_LINK_ARRAY);
		TERMINALS[127].addFollower(TERMINALS[112], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getStoffTag(), FEATURES[11]), });
		TERMINALS[127].addFollower(TERMINALS[113], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBenutzerTag(), FEATURES[11]), });
		TERMINALS[127].addFollower(TERMINALS[114], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getDiaetTag(), FEATURES[11]), });
		TERMINALS[127].addFollower(TERMINALS[115], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProduktRef(), FEATURES[14]), });
		TERMINALS[127].addFollower(TERMINALS[116], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getZutat(), FEATURES[15]), });
		TERMINALS[114].addFollower(TERMINALS[128], EMPTY_LINK_ARRAY);
		TERMINALS[128].addFollower(TERMINALS[129], EMPTY_LINK_ARRAY);
		TERMINALS[129].addFollower(TERMINALS[112], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getStoffTag(), FEATURES[11]), });
		TERMINALS[129].addFollower(TERMINALS[113], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBenutzerTag(), FEATURES[11]), });
		TERMINALS[129].addFollower(TERMINALS[114], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getDiaetTag(), FEATURES[11]), });
		TERMINALS[129].addFollower(TERMINALS[115], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProduktRef(), FEATURES[14]), });
		TERMINALS[129].addFollower(TERMINALS[116], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getZutat(), FEATURES[15]), });
		TERMINALS[115].addFollower(TERMINALS[130], EMPTY_LINK_ARRAY);
		TERMINALS[130].addFollower(TERMINALS[131], EMPTY_LINK_ARRAY);
		TERMINALS[131].addFollower(TERMINALS[132], EMPTY_LINK_ARRAY);
		TERMINALS[132].addFollower(TERMINALS[133], EMPTY_LINK_ARRAY);
		TERMINALS[133].addFollower(TERMINALS[115], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getProduktRef(), FEATURES[14]), });
		TERMINALS[133].addFollower(TERMINALS[116], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getZutat(), FEATURES[15]), });
		TERMINALS[116].addFollower(TERMINALS[134], EMPTY_LINK_ARRAY);
		TERMINALS[134].addFollower(TERMINALS[68], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBestimmteMenge(), FEATURES[16]), });
		TERMINALS[134].addFollower(TERMINALS[69], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getUnbestimmteMenge(), FEATURES[16]), });
		TERMINALS[68].addFollower(TERMINALS[135], EMPTY_LINK_ARRAY);
		TERMINALS[135].addFollower(TERMINALS[136], EMPTY_LINK_ARRAY);
		TERMINALS[135].addFollower(TERMINALS[137], EMPTY_LINK_ARRAY);
		TERMINALS[136].addFollower(TERMINALS[137], EMPTY_LINK_ARRAY);
		TERMINALS[137].addFollower(TERMINALS[138], EMPTY_LINK_ARRAY);
		TERMINALS[138].addFollower(TERMINALS[72], EMPTY_LINK_ARRAY);
		TERMINALS[138].addFollower(TERMINALS[73], EMPTY_LINK_ARRAY);
		TERMINALS[138].addFollower(TERMINALS[74], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getPreis(), FEATURES[9]), });
		TERMINALS[138].addFollower(TERMINALS[75], EMPTY_LINK_ARRAY);
		TERMINALS[138].addFollower(TERMINALS[76], EMPTY_LINK_ARRAY);
		TERMINALS[138].addFollower(TERMINALS[77], EMPTY_LINK_ARRAY);
		TERMINALS[138].addFollower(TERMINALS[116], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getZutat(), FEATURES[15]), });
		TERMINALS[138].addFollower(TERMINALS[117], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getArbeitsschritt(), FEATURES[17]), });
		TERMINALS[69].addFollower(TERMINALS[139], EMPTY_LINK_ARRAY);
		TERMINALS[139].addFollower(TERMINALS[72], EMPTY_LINK_ARRAY);
		TERMINALS[139].addFollower(TERMINALS[73], EMPTY_LINK_ARRAY);
		TERMINALS[139].addFollower(TERMINALS[74], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getPreis(), FEATURES[9]), });
		TERMINALS[139].addFollower(TERMINALS[75], EMPTY_LINK_ARRAY);
		TERMINALS[139].addFollower(TERMINALS[76], EMPTY_LINK_ARRAY);
		TERMINALS[139].addFollower(TERMINALS[77], EMPTY_LINK_ARRAY);
		TERMINALS[139].addFollower(TERMINALS[116], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getZutat(), FEATURES[15]), });
		TERMINALS[139].addFollower(TERMINALS[117], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getArbeitsschritt(), FEATURES[17]), });
		TERMINALS[117].addFollower(TERMINALS[140], EMPTY_LINK_ARRAY);
		TERMINALS[140].addFollower(TERMINALS[119], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getTipp(), FEATURES[18]), });
		TERMINALS[140].addFollower(TERMINALS[120], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getKommentar(), FEATURES[18]), });
		TERMINALS[140].addFollower(TERMINALS[121], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAnmerkung(), FEATURES[18]), });
		TERMINALS[140].addFollower(TERMINALS[117], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getArbeitsschritt(), FEATURES[17]), });
		TERMINALS[140].addFollower(TERMINALS[118], EMPTY_LINK_ARRAY);
		TERMINALS[119].addFollower(TERMINALS[141], EMPTY_LINK_ARRAY);
		TERMINALS[141].addFollower(TERMINALS[119], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getTipp(), FEATURES[12]), });
		TERMINALS[141].addFollower(TERMINALS[120], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getKommentar(), FEATURES[12]), });
		TERMINALS[141].addFollower(TERMINALS[121], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAnmerkung(), FEATURES[12]), });
		TERMINALS[141].addFollower(TERMINALS[122], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBild(), FEATURES[13]), });
		TERMINALS[141].addFollower(TERMINALS[123], EMPTY_LINK_ARRAY);
		TERMINALS[120].addFollower(TERMINALS[142], EMPTY_LINK_ARRAY);
		TERMINALS[142].addFollower(TERMINALS[119], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getTipp(), FEATURES[12]), });
		TERMINALS[142].addFollower(TERMINALS[120], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getKommentar(), FEATURES[12]), });
		TERMINALS[142].addFollower(TERMINALS[121], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAnmerkung(), FEATURES[12]), });
		TERMINALS[142].addFollower(TERMINALS[122], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBild(), FEATURES[13]), });
		TERMINALS[142].addFollower(TERMINALS[123], EMPTY_LINK_ARRAY);
		TERMINALS[121].addFollower(TERMINALS[143], EMPTY_LINK_ARRAY);
		TERMINALS[143].addFollower(TERMINALS[119], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getTipp(), FEATURES[12]), });
		TERMINALS[143].addFollower(TERMINALS[120], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getKommentar(), FEATURES[12]), });
		TERMINALS[143].addFollower(TERMINALS[121], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getAnmerkung(), FEATURES[12]), });
		TERMINALS[143].addFollower(TERMINALS[122], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBild(), FEATURES[13]), });
		TERMINALS[143].addFollower(TERMINALS[123], EMPTY_LINK_ARRAY);
		TERMINALS[106].addFollower(TERMINALS[144], EMPTY_LINK_ARRAY);
		TERMINALS[144].addFollower(TERMINALS[145], EMPTY_LINK_ARRAY);
		TERMINALS[145].addFollower(TERMINALS[146], EMPTY_LINK_ARRAY);
		TERMINALS[146].addFollower(TERMINALS[147], EMPTY_LINK_ARRAY);
		TERMINALS[147].addFollower(TERMINALS[104], EMPTY_LINK_ARRAY);
		TERMINALS[147].addFollower(TERMINALS[105], EMPTY_LINK_ARRAY);
		TERMINALS[107].addFollower(TERMINALS[148], EMPTY_LINK_ARRAY);
		TERMINALS[148].addFollower(TERMINALS[149], EMPTY_LINK_ARRAY);
		TERMINALS[149].addFollower(TERMINALS[150], EMPTY_LINK_ARRAY);
		TERMINALS[150].addFollower(TERMINALS[104], EMPTY_LINK_ARRAY);
		TERMINALS[150].addFollower(TERMINALS[105], EMPTY_LINK_ARRAY);
		TERMINALS[122].addFollower(TERMINALS[151], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getInternetPfad(), FEATURES[19]), });
		TERMINALS[122].addFollower(TERMINALS[152], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getLokalerPfad(), FEATURES[19]), });
		TERMINALS[153].addFollower(TERMINALS[157], EMPTY_LINK_ARRAY);
		TERMINALS[157].addFollower(TERMINALS[154], EMPTY_LINK_ARRAY);
		TERMINALS[157].addFollower(TERMINALS[155], EMPTY_LINK_ARRAY);
		TERMINALS[157].addFollower(TERMINALS[156], EMPTY_LINK_ARRAY);
		TERMINALS[154].addFollower(TERMINALS[158], EMPTY_LINK_ARRAY);
		TERMINALS[158].addFollower(TERMINALS[155], EMPTY_LINK_ARRAY);
		TERMINALS[158].addFollower(TERMINALS[156], EMPTY_LINK_ARRAY);
		TERMINALS[155].addFollower(TERMINALS[159], EMPTY_LINK_ARRAY);
		TERMINALS[159].addFollower(TERMINALS[156], EMPTY_LINK_ARRAY);
		TERMINALS[156].addFollower(TERMINALS[122], new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature[] {new com.github.funthomas424242.rezeptsammler.rezept.resource.rezept.mopp.RezeptContainedFeature(com.github.funthomas424242.rezeptsammler.rezept.RezeptPackage.eINSTANCE.getBild(), FEATURES[13]), });
		TERMINALS[156].addFollower(TERMINALS[123], EMPTY_LINK_ARRAY);
		TERMINALS[151].addFollower(TERMINALS[160], EMPTY_LINK_ARRAY);
		TERMINALS[160].addFollower(TERMINALS[153], EMPTY_LINK_ARRAY);
		TERMINALS[160].addFollower(TERMINALS[154], EMPTY_LINK_ARRAY);
		TERMINALS[160].addFollower(TERMINALS[155], EMPTY_LINK_ARRAY);
		TERMINALS[160].addFollower(TERMINALS[156], EMPTY_LINK_ARRAY);
		TERMINALS[152].addFollower(TERMINALS[161], EMPTY_LINK_ARRAY);
		TERMINALS[161].addFollower(TERMINALS[153], EMPTY_LINK_ARRAY);
		TERMINALS[161].addFollower(TERMINALS[154], EMPTY_LINK_ARRAY);
		TERMINALS[161].addFollower(TERMINALS[155], EMPTY_LINK_ARRAY);
		TERMINALS[161].addFollower(TERMINALS[156], EMPTY_LINK_ARRAY);
	}
	
	public static void wire() {
		wire0();
	}
	
	static {
		// initialize the arrays
		initializeTerminals();
		initializeFeatures();
		initializeLinks();
		// wire the terminals
		wire();
	}
}
